version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
artifacts:
  files:
    - '**/*'
  base-directory: .
  name: was-artifact
  discard-paths: no